DESCRIPTION
R/onload.R

Move debugme to Suggests

---

R/deps.R

Fix for --no-vanilla

---

R/deps-install.R

Extract deps_opts()

---

R/check.R
R/compare.R
R/results.R

Related to #81, but ttps://github.com/r-lib/rcmdcheck/pull/44 is needed to get rid of the error.

Need to print summary() now

---

R/event-loop.R

Fixes #98 
This fixes the issue with limited testing, @gaborcsardi please take a look and make sure this the right fix.

Only update progress bar if we are not completed.

---

R/revdepcheck.R

to enable caching from crancache

Use repos argument in call to install_local()

---

R/download.R
R/event-loop.R

Part of #126. Would also make sense to skip the package after 20 failures rather than throwing an error.

Attempt to download package tarball 20 times before failing

---

inst/templates/email-broken.txt

- highlight difference between breaking and non-breaking changes
- include custom paragraph

E-mail tweaks

---

R/email.R
inst/templates/email-broken.txt

Tweak e-mail

---

DESCRIPTION

Add crayon remote

---

DESCRIPTION
R/cloud.R

Using brio::read_file() to get into R and then iconv() to strip bad characters

Fix invalid utf-8 characters

---

DESCRIPTION
R/cloud.R
man/cloud_report.Rd

* Only write failures if requested
* Write CRAN comments too

Cloud reporting tweaks

---

DESCRIPTION
R/report.R

Instead of URL + BugReports
(untested since I don't remember how we test these functions)

Display GitHub home

---

R/cloud.R
man/cloud_broken.Rd
man/cloud_details.Rd
man/cloud_email.Rd
man/cloud_fetch_results.Rd
man/cloud_job.Rd
man/cloud_report.Rd
man/cloud_results.Rd
man/cloud_summary.Rd

Default to most recent cloud checks

---

R/cloud.R
R/report.R
R/utils.R

Truncate long messages

---

vignettes/cloud.Rmd

I just had to do refresh the SSO session today. I have no idea how regularly the AWS/Okta integration requires this, but it has been about a week since I last used a cloud function.

Add advice on refreshing the SSO session

---

R/cloud.R
man/cloud_check.Rd

Bump the default R version for `cloud_check()`

---

vignettes/cloud.Rmd

related to https://github.com/r-lib/revdepcheck/issues/307

Mention main branch instead of master.

---

R/db.R
R/revdepcheck.R

Disconnect from database before removing from cache

---

R/cloud.R

Fix `revdep/cran.md` hyperlink

---

R/report.R

* Move version into heading
* Drop fields that aren't that useful
* Drop `<details>` (not sure why it was here and not wrapping the potentially much longer failure info)
* Add maintainer email address
* Truncate failure info from start, not middle, and show more lines
@gaborcsardi I'm trying these all out with the testthat release, but it's worth thinking a little bit about these changes and if they're uniformly useful.

Polishing failure details

---

.github/workflows/R-CMD-check.yaml
.github/workflows/format-suggest.yaml
.github/workflows/pkgdown.yaml
.github/workflows/test-coverage.yaml
DESCRIPTION

* `use_tidy_github_actions()`
* `use_tidy_description()`
* Re-document

Upkeep 2025-09
